#include<iostream>
#include<math.h>
#include <string>
#include <cstdlib>
#include <ctime>
using namespace std;

string generate(int l , int lvl){
    string bucket="";
    if(lvl>=1){
        bucket = bucket + "abcdefghijklmnopqrstuvwxyz" ;
    }
    if(lvl>=2){
        bucket = bucket + "ABCDEFGHIJKLMNOPQRSTUVWXYZ" ;
    }
    if(lvl>=3){
        bucket = bucket + "0123456789" ;
    }
    if(lvl>=4){
        bucket = bucket + "!@#$%^&*()_+" ;
    }

    string pass = "" ;

    srand(time(NULL));

    for(int i=0;i<l;i++){
        pass = pass + bucket[rand() % bucket.length()];
    }

    return pass;
}

int main(){

    cout<<endl;
    cout<<"Enter the length of Password: "<<endl;
    int len;
    cin>>len;

    cout<<"Enter the level of your Password (1-4) : "<<endl;
    cout<<"Level-1: only includes lower case letters!"<<endl;
    cout<<"Level-2: add upper case letters to the password!"<<endl;
    cout<<"Level-3: add digits to your password!"<<endl;
    cout<<"Level-4: add special charater in your password"<<endl;

    cout<<endl;

    cout<<"Though this pass is generated by a random technique algorithm so it's not necessary that your password will surely contain it"<<endl;

    cout<<endl;
    
    cout<<"Enter level: "<<endl;
    int lvl;
    cin>>lvl;

    string pass = generate(len , lvl);
    
    cout<<"Your Password is : "<<pass<<endl;
    
    return 0;
}